version: '3.8'

services:
  web:
    image: tomcat:8.5-jre8
    ports:
      - "8080:8080"
    volumes:
      - ./target/spiderdiplome.war:/usr/local/tomcat/webapps/spiderdiplome.war
    environment:
      - DB_URL=
      - DB_USER=
      - DB_PASSWORD=
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
