name: Java Package with Maven

on: [push, pull_request]

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Package application
      run: mvn package
    - name: Archive the built artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/*.jar # ou target/*.war selon le type de projet
